sudo: required
services:
  - docker
before_install:
  - docker build -t strisen/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true strisen/react-test npm test
after_success:
  - docker build -t strisen/multi-client ./client
  - docker build -t strisen/multi-nginx ./nginx
  - docker build -t strisen/multi-server ./server
  - docker build -t strisen/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push strisen/multi-client
  - docker push strisen/multi-nginx
  - docker push strisen/multi-server
  - docker push strisen/multi-worker
